name: 书旗小说1
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '0 1,3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/wangzheroom/ACScripts.git ~/ACScripts
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x          
      - name: npm install
        run: |
          cd ~/ACScripts/Task        
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
          
      - name: '【书旗小说】'
        run: |  
          cd ~/ACScripts/Task
          node sqxs.js      
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
          




