name: 中青阅读1

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/wangzheroom/ACScripts.git ~/ACScripts
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/ACScripts
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读1】'
        run: |
          cd ~/ACScripts  
          node Task/Youth_AutoRead1.js
